### ISSUE TITLE
Undefined symbol in 8.1 for library built against 8.0

### ISSUE THREAD

**Issue by saraedum** [conda-forge/fmt-feedstock#27]
The symbol `_ZN3fmt2v86detail13error_handler8on_errorEPKc` was in 8.0 but is not in our 8.1 build anymore.

I am not sure why it is required but a [libintervalxt](https://github.com/conda-forge/intervalxt-feedstock/blob/master/recipe/meta.yaml#L37) library built against 8.0 is looking for that symbol; see [this error](https://github.com/flatsurf/flatsurf/runs/4698212878?check_suite_focus=true#step:6:554).

**Comment by saraedum** [comment]
I created an upstream issue at https://github.com/fmtlib/fmt/issues/2695.

**Comment by tdegeus** [comment]
It looks like an upstream bug. Let's centralise the discussion in https://github.com/fmtlib/fmt/issues/2695

**Comment by tdegeus** [comment]
Closing as https://github.com/fmtlib/fmt/issues/2695 was fixed
