### ISSUE TITLE
Version 10.1.1 reports itself as 10.1.0 in the CMake config.

### ISSUE THREAD

**Issue by bdice** [conda-forge/fmt-feedstock#37]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The 10.1.1 release of fmt didn't update the version in `core.h` from 10.1.0.

https://github.com/fmtlib/fmt/blob/10.1.1/include/fmt/core.h#L21

As a result, CMake thinks that the version is 10.1.0 instead of 10.1.1.

The version was updated in a [separate commit](https://github.com/fmtlib/fmt/commit/28e2d3b640d0705a9622b0393cfc4779277c089c) but it doesn't seem like that commit made it into the tag for 10.1.1.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by tdegeus** [comment]
Thanks for this. Just a question to @vitaut : it would be simpler here if you'd release a `v10.1.2` with the fixed (well, with the correct tag then ;)). Would that be something you would consider?

**Comment by bdice** [comment]
I would be happy to co-maintain!

**Comment by tdegeus** [comment]
Would you please add yourself then in the PR and rerender?

**Comment by vitaut** [comment]
This will be fixed by the next planned version.
