### ISSUE TITLE
fmt 10.2.0 not building for linux-aarch64 anymore?

### ISSUE THREAD

**Issue by thraneh** [conda-forge/fmt-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have noticed that fmt 10.2 wasn't available for linux-aarch64 anymore. Was it intentionally dropped for some reason?

### Installed packages

```shell
https://anaconda.org/conda-forge/fmt/files?version=10.2.0
```

### Environment info

```shell
https://anaconda.org/conda-forge/fmt/files?version=10.2.0
```

**Comment by tdegeus** [comment]
I would say that it should still be building:

https://github.com/conda-forge/fmt-feedstock/blob/f16e1dfff7461c910e762d0948860c86664b1267/conda-forge.yml#L3

**Comment by thraneh** [comment]
That's what I thought... But linux-aarch64 wasn't available from conda-forge for the past few days. Perhaps something build-system related overlapping with the recent pull requests (issues around libmamba and 10.1.1 vs 10.2)?

**Comment by tdegeus** [comment]
Indeed, I see that there was no upload : https://anaconda.org/conda-forge/fmt . It also seems that there was no build. Honestly, I don't know what is going on. We could try to re-render.

**Comment by thraneh** [comment]
Looks like that did the trick.

Thank you so much for helping out here!

**Comment by tdegeus** [comment]
Thanks for reporting!
