### ISSUE TITLE
fmt.dll ends up in wrong directory on Windows

### ISSUE THREAD

**Issue by robquant** [conda-forge/fmt-feedstock#5]
On Windows the shared library fmt.dll is installed in `%CONDA_PREFIX%\Library\lib` (as is the static lib fmt.lib). However, the canonical path for shared libs in conda environments is `%CONDA_PREFIX%\Library\bin`. Therefore the shared lib is not found when running a programm that is linked against it.

**Comment by tdegeus** [comment]
@robquant I'm not a Windows expert. Could you confirm that this https://github.com/fmtlib/fmt/pull/1432 would fix the issue?

**Comment by tdegeus** [comment]
@robquant Also can you confirm if/that CMake also still knows where to look on Windows?

**Comment by robquant** [comment]
@tdegeus I tried your fix, but needed to make some changes to it: https://github.com/fmtlib/fmt/pull/1437
With this the dll is copied to the right place and cmake is also able to link to it later.

**Comment by tdegeus** [comment]
Great @robquant ! 

It would be great @vitaut if you could release a new version if https://github.com/fmtlib/fmt/pull/1437 is merged. The alternative would be to add patches to the feedstock here (e.g. https://github.com/conda-forge/fmt-feedstock/pull/6 ), but given the number of commits since the last release this becomes a bit clumsy.

**Comment by tdegeus** [comment]
And thank @robquant for the report, and the improvement of my PR.

**Comment by robquant** [comment]
Thanks @tdegeus for pointing me to the right place in the CMakeLists.txt!

**Comment by vitaut** [comment]
I'm currently working on putting together a new release and https://github.com/fmtlib/fmt/pull/1437 can be part of it.

**Comment by tdegeus** [comment]
@robquant Can you confirm that this issue is fixed in version 6.1.0

**Comment by robquant** [comment]
@tdegeus Yes, fmt.dll is now in the right place!
